---
# tasks file for AnsibleTest
  - name: Ensure epel is enabled
    yum:
      name: epel-release
      state: installed

  - name: Ensure additional packages are installed
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - "{{ additional_packages }}"

  - name: Template out python installation script
    template:
      src: install_python_version.sh.j2
      dest: "/home/vagrant/{{ item | basename | replace('.tgz', '') }}.sh"
      mode: 0700
    with_items:
      - "{{ python_versions }}"

  - name: Execute Python installation scripts if required
    shell: "/home/vagrant/{{ item | basename | replace('.tgz', '') }}.sh"
    args:
      creates: "/home/vagrant/install_{{ item | basename | replace('.tgz', '') }}.success"
    with_items:
      - "{{ python_versions }}"

  - name: Ensure python environments are setup
    script: bash/install_setup_tools_pip.sh
    args:
      creates: /home/vagrant/py_setuptools_pip.success

  - name: Ensure git dir exists in vagrant home
    file:
      name: /home/vagrant/git
      state: directory
      mode: 0755
      owner: vagrant
      group: vagrant

  - name: Git clone projects
    git:
      repo: "{{ item }}"
      dest: "/home/vagrant/git/{{ item | basename | replace('.git', '') }}"
      update: "{{ update_git }}"
    become: no
    with_items:
      - "{{ git_repos }}"

  - name: Add MongoDB yum repo
    yum_repository:
      name: MongoDB36_Repository
      description: MongoDB 3.6 Repository
      baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.6/x86_64/
      gpgcheck: yes
      enabled: yes
      gpgkey: https://www.mongodb.org/static/pgp/server-3.6.asc
    notify: yum-clean-metadata

  - name: Ensure MongoDB packages are installed
    yum:
      name: mongodb-org
      state: installed

  - name: Ensure aliases exist
    lineinfile:
      path: /home/vagrant/.bash_profile
      regexp: '^alias {{ item }}'
      line: "alias {{ item }}"
    become: no
    with_items:
      - "{{ aliases }}"

  - name: Ensure bash scripts needed for testing are present
    copy:
      src: "{{ item }}"
      dest: /home/vagrant/bash/
      owner: vagrant
      group: vagrant
      mode: 0755
    with_fileglob: bash/*.sh

  - name: Ensure playbooks needed for testing are present
    copy:
      src: "{{ item }}"
      dest: /home/vagrant/playbooks/
      owner: vagrant
      group: vagrant
    with_fileglob: playbooks/*.yml

  - name: Ensure current-ignore.txt is updated appropriately
    lineinfile:
      path: /home/vagrant/git/ansible/test/sanity/pep8/current-ignore.txt
      regexp: "^{{ item }}$"
      line: "{{ item }}"
    become: no
    with_items:
      - W605
